Add message-broker to development.sh
IMGIITRoorkee/omniport-docker pull request #31
Opened 2020-09-23 16:16 UTC by gagansh7171

2020-09-23 16:42 UTC, dhruvkb requested changes
LGTM except for a minor change.

2020-09-23 16:42 UTC, dhruvkb commented on scripts/start/development.sh
> +    cache\
```suggestion
    cache \
```

2020-09-23 17:13 UTC, gagansh7171 commented
Committed requested change.

2020-09-23 23:34 UTC, dhruvkb approved these changes

2020-09-24 04:21 UTC, merged

2020-09-24 04:21 UTC, algomaster99 commented
@gagansh7171 good work with writing commit messages. :smile: